// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: households.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createHousehold = `-- name: CreateHousehold :exec
 CALL create_household( $1, $2 )
`

type CreateHouseholdParams struct {
	Name   string
	Userid uuid.UUID
}

func (q *Queries) CreateHousehold(ctx context.Context, arg CreateHouseholdParams) error {
	_, err := q.db.Exec(ctx, createHousehold, arg.Name, arg.Userid)
	return err
}
