// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: households.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createHousehold = `-- name: CreateHousehold :exec
CALL create_household($1, $2)
`

type CreateHouseholdParams struct {
	HouseholdName string
	UserID        uuid.UUID
}

func (q *Queries) CreateHousehold(ctx context.Context, arg CreateHouseholdParams) error {
	_, err := q.db.Exec(ctx, createHousehold, arg.HouseholdName, arg.UserID)
	return err
}

const deleteHousehold = `-- name: DeleteHousehold :exec
CALL user_delete_household($1, $2)
`

type DeleteHouseholdParams struct {
	UserID      uuid.UUID
	HouseholdID uuid.UUID
}

func (q *Queries) DeleteHousehold(ctx context.Context, arg DeleteHouseholdParams) error {
	_, err := q.db.Exec(ctx, deleteHousehold, arg.UserID, arg.HouseholdID)
	return err
}

const getHouseholdById = `-- name: GetHouseholdById :one
SELECT id, created_at, updated_at, name FROM households
WHERE id = $1
`

func (q *Queries) GetHouseholdById(ctx context.Context, id uuid.UUID) (Household, error) {
	row := q.db.QueryRow(ctx, getHouseholdById, id)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}

const getHouseholdByUserId = `-- name: GetHouseholdByUserId :one
SELECT h.id, h.created_at, h.updated_at, h.name FROM households h
INNER JOIN household_members m ON ( h.id = m.household_id )
INNER JOIN users u ON ( m.user_id = u.id )
WHERE u.id = $1
`

func (q *Queries) GetHouseholdByUserId(ctx context.Context, id uuid.UUID) (Household, error) {
	row := q.db.QueryRow(ctx, getHouseholdByUserId, id)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}

const updateHousehold = `-- name: UpdateHousehold :exec
CALL user_update_household($1::uuid, $2::uuid, $3::text)
`

type UpdateHouseholdParams struct {
	UserID      uuid.UUID
	HouseholdID uuid.UUID
	NewName     string
}

// CALL user_update_household($1, $2, $3);
func (q *Queries) UpdateHousehold(ctx context.Context, arg UpdateHouseholdParams) error {
	_, err := q.db.Exec(ctx, updateHousehold, arg.UserID, arg.HouseholdID, arg.NewName)
	return err
}
