// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: household_members.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const acceptHouseholdInvite = `-- name: AcceptHouseholdInvite :exec
CALL accept_household_invite($1, $2)
`

type AcceptHouseholdInviteParams struct {
	InviteeID   uuid.UUID
	HouseholdID uuid.UUID
}

func (q *Queries) AcceptHouseholdInvite(ctx context.Context, arg AcceptHouseholdInviteParams) error {
	_, err := q.db.Exec(ctx, acceptHouseholdInvite, arg.InviteeID, arg.HouseholdID)
	return err
}

const createHouseholdMember = `-- name: CreateHouseholdMember :exec
CALL user_create_household_member($1, $2, $3, $4)
`

type CreateHouseholdMemberParams struct {
	CreatorID   uuid.UUID
	MemberName  string
	UserID      *uuid.UUID
	HouseholdID uuid.UUID
}

func (q *Queries) CreateHouseholdMember(ctx context.Context, arg CreateHouseholdMemberParams) error {
	_, err := q.db.Exec(ctx, createHouseholdMember,
		arg.CreatorID,
		arg.MemberName,
		arg.UserID,
		arg.HouseholdID,
	)
	return err
}

const declineHouseholdInvite = `-- name: DeclineHouseholdInvite :one
DELETE FROM household_invites
WHERE invitee_id = $1 AND household_id = $2
returning inviter_id, invitee_id, household_member_id, household_id, created_at
`

type DeclineHouseholdInviteParams struct {
	InviteeID   uuid.UUID
	HouseholdID uuid.UUID
}

func (q *Queries) DeclineHouseholdInvite(ctx context.Context, arg DeclineHouseholdInviteParams) (HouseholdInvite, error) {
	row := q.db.QueryRow(ctx, declineHouseholdInvite, arg.InviteeID, arg.HouseholdID)
	var i HouseholdInvite
	err := row.Scan(
		&i.InviterID,
		&i.InviteeID,
		&i.HouseholdMemberID,
		&i.HouseholdID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteHouseholdMember = `-- name: DeleteHouseholdMember :exec
CALL user_delete_household_member($1, $2)
`

type DeleteHouseholdMemberParams struct {
	UserID            uuid.UUID
	HouseholdMemberID uuid.UUID
}

func (q *Queries) DeleteHouseholdMember(ctx context.Context, arg DeleteHouseholdMemberParams) error {
	_, err := q.db.Exec(ctx, deleteHouseholdMember, arg.UserID, arg.HouseholdMemberID)
	return err
}

const getHouseholdInvites = `-- name: GetHouseholdInvites :many
SELECT inviter_id, invitee_id, household_member_id, household_id, created_at FROM household_invites
WHERE inviter_id = $1 OR invitee_id = $1
`

func (q *Queries) GetHouseholdInvites(ctx context.Context, inviterID uuid.UUID) ([]HouseholdInvite, error) {
	rows, err := q.db.Query(ctx, getHouseholdInvites, inviterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HouseholdInvite
	for rows.Next() {
		var i HouseholdInvite
		if err := rows.Scan(
			&i.InviterID,
			&i.InviteeID,
			&i.HouseholdMemberID,
			&i.HouseholdID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHouseholdMember = `-- name: GetHouseholdMember :one
SELECT id, name, created_at, updated_at, role, household_id, user_id FROM household_members
WHERE id = $1
`

func (q *Queries) GetHouseholdMember(ctx context.Context, id uuid.UUID) (HouseholdMember, error) {
	row := q.db.QueryRow(ctx, getHouseholdMember, id)
	var i HouseholdMember
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.HouseholdID,
		&i.UserID,
	)
	return i, err
}

const getHouseholdMembers = `-- name: GetHouseholdMembers :many
SELECT id, name, created_at, updated_at, role, household_id, user_id FROM household_members
WHERE household_id = $1
`

func (q *Queries) GetHouseholdMembers(ctx context.Context, householdID uuid.UUID) ([]HouseholdMember, error) {
	rows, err := q.db.Query(ctx, getHouseholdMembers, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HouseholdMember
	for rows.Next() {
		var i HouseholdMember
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
			&i.HouseholdID,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const inviteUserToHousehold = `-- name: InviteUserToHousehold :exec
CALL invite_user_to_household($1, $2, $3, $4)
`

type InviteUserToHouseholdParams struct {
	Inviter           uuid.UUID
	Invitee           uuid.UUID
	HouseholdID       uuid.UUID
	HouseholdMemberID uuid.UUID
}

func (q *Queries) InviteUserToHousehold(ctx context.Context, arg InviteUserToHouseholdParams) error {
	_, err := q.db.Exec(ctx, inviteUserToHousehold,
		arg.Inviter,
		arg.Invitee,
		arg.HouseholdID,
		arg.HouseholdMemberID,
	)
	return err
}

const updateHouseholdMember = `-- name: UpdateHouseholdMember :exec
CALL user_update_household_member($1, $2, $3, $4, $5)
`

type UpdateHouseholdMemberParams struct {
	UpdaterID         uuid.UUID
	NewName           string
	NewRole           int
	NewUserID         uuid.UUID
	HouseholdMemberID uuid.UUID
}

func (q *Queries) UpdateHouseholdMember(ctx context.Context, arg UpdateHouseholdMemberParams) error {
	_, err := q.db.Exec(ctx, updateHouseholdMember,
		arg.UpdaterID,
		arg.NewName,
		arg.NewRole,
		arg.NewUserID,
		arg.HouseholdMemberID,
	)
	return err
}
