// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Household struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
}

type HouseholdInvite struct {
	InviterID         uuid.UUID
	InviteeID         uuid.UUID
	HouseholdMemberID uuid.UUID
	HouseholdID       uuid.UUID
	CreatedAt         time.Time
}

type HouseholdMember struct {
	ID          uuid.UUID
	Name        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Role        int
	HouseholdID uuid.UUID
	UserID      uuid.UUID
}

type HouseholdRole struct {
	ID   int
	Name string
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	ExpiresAt time.Time
	RevokedAt time.Time
}

type User struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Name           string
	Email          string
	HashedPassword string
}
