// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Household struct {
	ID        uuid.UUID
	CreatedAt time.Time
	Name      string
}

type HouseholdMember struct {
	ID          uuid.UUID
	Name        pgtype.Text
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Role        pgtype.Int4
	HouseholdID pgtype.UUID
	UserID      pgtype.UUID
}

type HouseholdRole struct {
	ID   int32
	Name string
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	ExpiresAt time.Time
	RevokedAt pgtype.Timestamp
}

type User struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Name           string
	Email          string
	HashedPassword string
}
