// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reset.sql

package database

import (
	"context"
)

const resetHouseholds = `-- name: ResetHouseholds :exec
DELETE FROM households
`

func (q *Queries) ResetHouseholds(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetHouseholds)
	return err
}

const resetUsers = `-- name: ResetUsers :exec
DELETE FROM users
`

func (q *Queries) ResetUsers(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetUsers)
	return err
}
